### ISSUE TITLE
parameter attribute names and component names aren't idential

### ISSUE THREAD

**Issue by Lukas-Kunz** [ZEN-universe/ZEN-garden#383]
attribute names and component names must be made identical (to assign units read from attribute files to component parameters).

E.g. attribute name = capex_specific, but component name = capex_specific_conversion/storage/technology

**Comment by johburger** [comment]
Is this also resolved with the closed issue #358? @fradmm ?

**Comment by fradmm** [comment]
Yes, it is solved now.
