### ISSUE TITLE
Turn energy_system files into jsons

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-garden#502]
e.g. base_units.csv, set_edges.csv, set_nodes.csv etc.

**Comment by johburger** [comment]
I already implemented the base_units file to a json format. For the long tables of set_edges (and also set_nodes) I don't see the advantage of the json. In my opinion it just makes the file messier and less readable.

**Comment by jacob-mannhardt** [comment]
agreed! I think we can leave it like this
