### ISSUE TITLE
Dataset tutorial improvements

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-garden#575]
- [x] **6_PWA_nonlinear_capex**: unit cost gets higher for larger capacities - doesn't make sense
    - updated in https://zen-garden.readthedocs.io/en/latest/files/input_handling.html#piece-wise-affine-input-data, check if that works in the code as well

**Comment by johburger** [comment]
Changed data in dataset examples and adjusted how the `nonlinear_capex.csv` file should be set up.
